// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwU1Tch824n_bPKJzA2DGRmNVYO-6S4KQ',
    appId: '1:1035673747757:web:b7f481c0f3737dace793a4',
    messagingSenderId: '1035673747757',
    projectId: 'tunelikes',
    authDomain: 'tunelikes.firebaseapp.com',
    storageBucket: 'tunelikes.appspot.com',
    measurementId: 'G-7JNZB6WR3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPzwRP-fg1sQHEKcc42K6kNRZd347IxI',
    appId: '1:1035673747757:android:b4cc23d856dac4e8e793a4',
    messagingSenderId: '1035673747757',
    projectId: 'tunelikes',
    storageBucket: 'tunelikes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4329XAUUxPPllcjHC4Pgn7Gb5FP3sCWM',
    appId: '1:1035673747757:ios:593042b3942778cfe793a4',
    messagingSenderId: '1035673747757',
    projectId: 'tunelikes',
    storageBucket: 'tunelikes.appspot.com',
    iosClientId:
        '1035673747757-sql14o0vn0edl5v2df1s9nfmsatd0n24.apps.googleusercontent.com',
    iosBundleId: 'com.tunelike.tunelike',
  );
}
